Add source files and database
fpmi-tp2024/tpmp-gpd-lab5-death-pact pull request #2
Opened 2024-03-25 15:20 UTC by qmafog

Check telegram messege

2024-03-25 17:29 UTC, IronGunYT requested changes

2024-03-25 17:29 UTC, IronGunYT commented on src/CMakeLists.txt
> +add_library(usersDAO usersDAO.cpp)
я бы DAO и относящийся к ней класс в один файл пихал
и подключал тоже вместе

2024-03-25 17:29 UTC, IronGunYT commented on src/carsDAO.cpp
> +static int f_select(void *sql_data, int argc, char **argv, char **azColName){
по названию функции f_select не выкупаю что она делает, давай хотя бы коммент добавим, или название понятнее

2024-03-25 17:29 UTC, IronGunYT commented on src/carsDAO.cpp
> +                            "VALUES ('" + car.getNumber() + "', '" + car.getBrand() + "', " + std::to_string(car.getInitialMileage()) + ", " + std::to_string(car.getCapacity()) + "); ";
подстановку параметров в sql запрос нужно делать встроенными функциями - они там их аккуратно экранируют. Подозреваю, что в sql_data можно их запихнуть
если оставить как есть, будет sql injection с возможностью дропнуть все базки из консоли пользователя

2024-03-25 17:29 UTC, IronGunYT commented on src/carsDAO.cpp
> +                            "VALUES ('" + car.getNumber() + "', '" + car.getBrand() + "', " + std::to_string(car.getInitialMileage()) + ", " + std::to_string(car.getCapacity()) + "); ";
пример: я вместо какой-нибудь строки(например, последнего параметра) по типу "my_favourite_car" ввожу следующее:
```
'); DROP TABLE cars; --
```

Что выходит: 
```sql
INSERT INTO cars (number,brand,initial_mileage,capacity)
VALUES ('1234', 'other_param', ..., ''); DROP TABLE cars; --');
```
где `--` - это коммент, и дальше уже ничего не будет смотреться

2024-03-25 17:29 UTC, IronGunYT commented on src/driver.cpp
> +    value = strtok(nullptr, delim);
тут nullptr потому что не доделал или забыл поправить?

2024-03-25 17:29 UTC, IronGunYT commented on src/driversDAO.cpp
> +                          "GROUP BY id " \
id есть и там и там

вообще вроде неплохой практикой является давать alias-ы таблицам при джойне
по типу:
```sql
SELECT * FROM drivers INNER JOIN orders ON d.id = o.driver_id WHERE d.id == ??...
```

2024-03-25 17:29 UTC, IronGunYT commented on src/driversDAO.cpp
> +    sqlite3 *db;
нужна валидация юзера, мы же не просто так его передаем

можно бахнуть функцию вида
`check_access(user, required_privileges (admin, ...))`

сюда доступ только у админов

2024-03-25 17:29 UTC, IronGunYT commented on src/driver.cpp
> +    char* value = strtok(sql_data.data(), delim);
там же подписаны элементы колонки, т.е. словарь вида `id: <id>, key: <value>`?
или просто значения подряд?

ты если делаешь `SELECT *` у тебя порядок может поменяться

2024-03-25 17:29 UTC, IronGunYT commented on include/car_park/car.hpp
> +
к `ext/autopark.db` (github не дает написать) - нужно в .gitignore, и удалить из гита

и папки с миграциями (sql файлы запускаемые для создания бд) не наблюдаю

2024-03-25 17:29 UTC, IronGunYT commented on include/car_park/order.hpp
> +    long long getDatetime() {
почему в половине кода snake_case, а в половине camelCase ;(

ну лан, тут code style, опционально

2024-03-25 17:29 UTC, IronGunYT commented on src/CMakeLists.txt
> +add_library(usersDAO usersDAO.cpp)
и вообще странно, что это всё отдельные либы

хотелось бы уметь одним include при желании подключать

2024-03-25 17:30 UTC, IronGunYT requested changes

2024-03-25 17:30 UTC, IronGunYT commented on include/car_park/car.hpp
> +    std::string number;
тестовый тык

2024-03-25 17:34 UTC, IronGunYT requested changes

2024-03-25 17:34 UTC, IronGunYT commented on include/car_park/user.hpp
> +    std::string type;
давай enum под это бахнем

2024-04-03 09:23 UTC, qmafog commented on src/driversDAO.cpp
> +    sqlite3 *db;
Валидация добавлена в driver и order

2024-04-03 09:24 UTC, qmafog commented on src/driver.cpp
> +    char* value = strtok(sql_data.data(), delim);
SELECT * не использую, порядок колонок указываю явно

2024-04-14 18:29 UTC, merged